config/routes.rb
Ibrokers::Application.routes.draw do

  devise_for :users
  get "welcome/index"
  get "/about_us", to: "welcome#about_us"
  get "/why_ibrokers", to: "welcome#why_ibrokers"
  get "/personal", to: "welcome#personal_ibrokers"
  get "/business", to: "welcome#business_ibrokers"
  get "/buy_online", to: "welcome#buy_online"
  get "/your_risk", to: "welcome#your_risk"
  get "/insurance_partner", to: "welcome#insurance_partner"
  get "/acc_cover", to: "welcome#acc_cover"
  get "/contact_us", to: "welcome#contact_us"
  root to: 'welcome#index'

  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index
  	@slider_categories = [
  		{image: 'assets/carousel-image.png',title: 'Adviser Net' , description: "Our website has changed, but our commitment to you never will.", url: '#'},
  		{image: 'assets/Protection-2.jpg',title: 'acc cover + extra' , description: 'Our website has changed, but our commitment to you never will.', url: '#'},
  		{image: 'assets/carousel-image.png',title: 'business and house insurance quote' , description: 'Our website has changed, but our commitment to you never will.', url: '#'},
  		{image: 'assets/Music Carnival.jpg',title: 'win a trip to fiji' , description: 'Our website has changed, but our commitment to you never will.', url: '#'}
  	]
  end

  def about_us
  	@page_title = "Ibrokers - About Us"
  end

  def why_ibrokers
  	@page_title = "Ibrokers - Why Us"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def resource_name
		:user
	end

	def resource
		@resource ||= User.new
	end

	def devise_mapping
		@devise_mapping ||= Devise.mappings[:user]
	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<link rel="shortcut icon" href="/assets/Colour-Logo-with-Slogan2.jpg"/>
	<title><%= @page_title || "Ibrokers" %> </title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
</head>

<body>
	<div class="sidebar-modal">
	</div>
	<div id="login-sidebar" class="sidebar">
		<button type="button" class="close sidebar-close">&times;</button>
		<%= render template: 'devise/sessions/new' %>
	</div>

	<div id="register-sidebar" class="sidebar">
		<button type="button" class="close sidebar-close">&times;</button>
		<%= render template: 'devise/registrations/new' %>
	</div>
	<div id="wrap">
		<div class="container-fluid">
			<div class="header row">
				<div class="col-sm-3">
					<%= link_to image_tag("IBL Logo.png", alt: "Logo"), root_url %>
				</div>
				<div class="col-sm-9 header-height">
					<div class="pull-right">
						<ul class="header-links">
							<li><a href="#" class="blue-link">File a claim</a></li>
							<li><%= link_to 'Contact us', contact_us_path %></li>
							<li><a href="https://www.facebook.com/Ibrokersnz" target="_blank" class="blue-link"><span class="icon icon-facebook"></span></a></li>
							<li><a href="#" class="blue-link"><span class="icon icon-twitter"></span></a></li>
							<% if user_signed_in? %>
							<%= link_to "LOGOUT", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
							<% else %>
							<div class="btn-group">
								<button type="button" data-sidebar="#login-sidebar" class="btn btn-danger btn-user">LOGIN</button>
								<button type="button" data-sidebar="#register-sidebar" class="btn btn-danger btn-user">REGISTER</button>
							</div>
							<% end %>
						</ul>
					</div>
				</div>
			</div>
			<% if notice %>
			<div class="row">
				<div class="col-sm-12">
					<div class="alert alert-info alert-dismissable">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						<%= notice %>
					</div>
				</div>
			</div>
			<% end %>
			<% if alert %>
			<div class="row">
				<div class="col-sm-12">
					<div class="alert alert-danger alert-dismissable">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						<%= alert %>
					</div>
				</div>
			</div>
			<% end %>
			<div class="row subheader-borders">			
				<ul class="nav navbar-nav">
					<li class="dropdown">
						<%= link_to 'HOME', root_url, class: "nav-subheading" %>
					</li>
					<li class="dropdown">
						<a class="nav-subheading" href="#">ABOUT IBL<b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><%= link_to 'Vision', about_us_path %></li>
							<li><%= link_to 'Why Us', why_ibrokers_path %></li>
						</ul>
					</li>
					<li class="dropdown">
						<a class="nav-subheading" href="#">SERVICE AND PRODUCTS<b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><%= link_to 'Personal', personal_path %></li>
							<li><%= link_to 'Business', business_path %></li>
						</ul>
					</li>
					<li class="dropdown">
						<a class="nav-subheading" href="#">ADVICE<b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><%= link_to 'Your Risk', your_risk_path %></li>
							<li><%= link_to 'Why Use A Broker', why_ibrokers_path %></li>
							<li><%= link_to 'Insurance Partner', insurance_partner_path %></li>
							<li><%= link_to 'ACC Cover + Extra', acc_cover_path %></li>
						</ul>
					</li>
				</ul>
				<form id="search-form" class="nav navbar-form navbar-right" role="search">
					<div class="form-group">
						<input type="text" class="search-input" placeholder="Search">
					</div>
					<button type="submit" class="search-button"><span class="glyphicon glyphicon-search search-icon"></span></button>
				</form>	
			</div>
		</div>		

		<div class="container-fluid">
			<%= yield %>	
		</div>
	</div>
	<div class="footer container-fluid">
		<div class="row">
			<div class="col-sm-12">
				<div class="pull-left">
					Copyright &copy; 2011-2014 IBL. All rights reserved.
				</div>
				<div class="pull-right">
					<ul class="footer-links-list">
						<li>
							<a href="#" class="blue-link footer-link">Online Privacy and Security Statement</a>
						</li>
						<li>
							<a href="#" class="blue-link footer-link">Usage Agreement</a>
						</li>
					</ul>

				</div>
			</div>
		</div>		
	</div>
</body>
</html>

app/views/welcome/_slider.html.erb
<% categories.each do |category| %>
<div class="slide">
	<div class="row">
		<div class="col-xs-4">
			<img src="<%= category[:image] %>">
		</div>
		<div class="col-xs-8">
			<h3><%= category[:title] %></h3>
			<hr>
			<p><%= category[:description] %></p>
			<a href="<%= category[:url] %>"><span class="text">Learn more</span></a>
		</div>
	</div>
</div>
<% end %>

app/views/welcome/about_us.html.erb
<div id="banner" class="banner-default">
	<h1>Vision</h1>
</div>

<div class="banner-header">
	<div id="vision" class="row">
		<div class="col-sm-12">
			<h3 class="about-heading">Vision</h3>
			<div>
				IB Ltd is committed to provide simplified solutions by engaging in sustainable practices and anticipating the needs of its customers.
			</div>
		</div>
	</div>
	<div id="about_us" class="row">
		<div class="col-sm-12">
			<h3 class="about-heading">About Us</h3>
			<div>
				<p>
					At IB Ltd we pride ourselves of providing best suited advice of personal risk and general insurance needs of our clients.
				</p>
				<p>
					Our Advisers have wealth of knowledge and experience to deliver what we promise. 
				</p>
				<p>
					We are based in Greater Hamilton and Auckland but cater clients all over New Zealand.
				</p>
				<ol>
					<li>We are driven by insurance solution than commission and always keeping the cost in mind.</li>
					<li>We have partnered with most of the major personal risk insurance companies to deliver the best in the market.</li>
					<li>We are part of Insurance advisernet to provide the general insurance solutions. Insurance Advisernet was established in 2006 as a joint venture between Insurance Advisernet Australia (IAA) and New Zealand investors. In April 2010 IAA took a majority shareholding in New Zealand, providing us with memebership of Austbrokers (a public listed company in Australia). The Austbrokers Group, including Insurance Advisernet, has over $2bn of client premiums under management.</li>
				</ol>
			</div>
		</div>
	</div>
	<div id="learning-insurance" class="row">
		<div class="col-sm-12">
			<h3 class="about-heading">Learning Information, Market Study/Analysis(Creating Understanding Of Insurance)</h3>
			<div>
				<h4>Why Insurance</h4>
				<p>
					You've worked hard to build a solid financial footing for you and your family, so you want to be sure that everything is protected. Accidents and unexpected events can and do happen, and if you aren’t adequately insured, it could leave you in financial ruin. You need insurance to protect your life, your ability to earn income, and to keep a roof over your head.
				</p>
			</div>
		</div>
	</div>
</div>

app/views/welcome/acc_cover.html.erb
<div id="banner" class="banner-default">
	<h1>Acc Cover</h1>
</div>

<div class="banner-header">
	<div class="row">
		<div class="col-sm-12">
			<p>If you are Self Employed or non-PAYE shareholder and paying to much ACC Bill. We can help you to Tailor your ACC bill which will not only match your needs but you will have better control over your ACC bill.</p>
			
			<p>Advantge of ACC Cover + Extra :</p>
			<ul>
				<li><b>ACC CoverPlusExtra is available to all self-employed and non-PAYE shareholder-employees</b></li>
				<li><b>You negotiate your level of lost	earnings cover.</b></li>
				<li><b> You receive 100% of this lost earnings cover if you can’t work because of aninjury, starting one week after your injury.</b></li>
				<li><b>You don’t have to prove loss of earnings when you make a claim.</b></li>
				<li><b>You have access to medical	and work-related help as part of your ACC CoverPlus Extra policy.</b></li>
			</ul>
		</div>
	</div>
</div>

app/views/welcome/business_ibrokers.html.erb
<div id="banner" class="banner-default">
	<h1>Business Insurance</h1>
</div>

<div class="banner-header">
	<div class="row">
		<div class="col-sm-12">
			<div>
				<p>
					To protect your business and run smoothly in face of adversity adequate cover is critical. Having business insurance can protect your assets. stock, vehicles and even your profit! 
				</p>
				<p>
					We provide solutions for a full range of Fire & General Insurance including:
				</p>
				<ul>
					<li><b>Business Insurance</b></li>
					<li><b>House and Content</b></li>
					<li><b>Rural Insurance</b></li>
					<li><b>Commercial Property</b></li>
					<li><b>Commercial Vehicle</b></li>
				</ul>
			</div>
		</div>

		<div class="col-sm-12">
			<h4 class="about-heading">Business Insurance</h4>
			<div>
				<p>
					Business Interruption Cover is very important – this sometimes can be the sole reason that many businesses don’t survive a major loss. For example, when a disaster strikes, a business may have to let key staff go because they can’t pay them. Then, when the business is ready to re-open, these skilled people have found other jobs. If machinery is covered for breakdown, but not Business Interruption, there is no cover for lost turnover while a machine is being repaired or replaced.
				</p>
				<p>
					Be certain that your cover allows enough time after an incident to clear up, complete the design process, consent process, to find tradesmen, order and receive any specialized plant or equipment, to test and commission it, to rebuild assets, to regain lost customers and lost orders and to return to the profitability enjoyed before the event
				</p>
				
				<div style="margin-top:20px">	
					<h4 class="about-heading">Liability Cover </h4>
					<div>
						<p> Liability cover gives protection to third party caused by your business. For e.g.</p>
						<p> Causing damage to another person’s property </p>
						<p> Breaching a legal statute such as the Resource Management Act</p>
						<p> Dealing with a personal grievance from an employee </p>
						<p> Causing damage or injury through a failure of a product or service you are selling</p>
					</div>
				</div>
				
				<div style="margin-top:20px">	
					<h4 class="about-heading">Material Damage /Business Asset</h4>
					<div>
						<p>
							Most common and important business cover. It mainly covers the stock and Plant of the business.
						</p>
					</div>
				</div>
			</div>
		</div>


		<div class="col-sm-12">
			<h4 class="about-heading">Rural Insurance </h4>
			<div>
				<p>
					We understand that every farm is different and there is no one-size-fits-all solution when it comes to rural insurance. In New Zealand we manage a wide range of rural insurance clients Horticulture / Dairy / Beef/ Agriculture.
				</p>
				<p>
					Our experience and access to an even wider range of Insurers means that we can find the most appropriate cover to protect against the kind of risks unique to farming.
				</p>
				<p>
					We can provide you with cover for storm damage, machinery catching fire or suffering damage, theft of vehicles or equipment and more. Adequate cover for your farm may involve insuring against the risk of an injury to you or another person from an animal on your property
				</p>
				<dv style="margin-top:15px">
					<p>Accidental Damage covering</p>
					<p>Buildings</p>
					<p>Contents</p>
					<p>Fences</p>
					<p>Hay,silage and grain</p>
					<p>Immobile machinery </p>
					<p>Unspecified mobile machinery</p>
				</div>
				<p>
					We can also ensure your farm insurance cover enables your farm to stay in business while it is recovering from an insured event.
				</p>
			</div>
		</div>


		<div class="col-sm-12">
			<h4 class="about-heading">Home and Content </h4>
			<div>
				<p>
					Contents insurance is insurance that pays for damage to, or loss of, a person’s personal possessions whilst they are located within that person’s home. Some contents insurance policies also provide restricted cover for personal possessions temporarily taken away from the home by the policyholder.
				</p>
				<p>
					House insurance to cover in case of disasters happen.
				</p>
			</div>
		</div>


		<div class="col-sm-12">
			<h4 class="about-heading">Commercial Property </h4>
			<div>
				<p>
					Insurance that is used to cover any type of commercial property. Commercial property insurance protects commercial property from such events such as fire, theft and natural disaster. This type of insurance should be undertaken by any business, including manufacturers, retailers, service-oriented businesses and not-for-profit organizations.
				</p>
			</div>
		</div>
		
		
		<div class="col-sm-12">
			<h4 class="about-heading">Commercial Vehicle</h4>
			<div>
				<p>
					Whether your business relies on cars, trucks, utes or even forklifts, insuring your commercial vehicles helps to protect an important asset for your 
				</p>
			</div>
		</div>

	</div>
</div>

app/views/welcome/buy_online.html.erb
<div class="row">
	<div class="col-sm-2 buy-online-sidebar">
		<div class="row">
			<div class="col-sm-12">
				<a disabled class="btn btn-warning btn-full"><span class="glyphicon glyphicon-phone"></span>Phone 0800-425-000</a>
				<a class="btn btn-primary btn-full"><span class="icon icon-coffee"></span>Make an appointment <br> with IBrokers</a>
				<a class="btn btn-primary btn-full"><span class="glyphicon glyphicon-envelope"></span>Email IBrokers</a>
			</div>
		</div>
		<div class="row">
			<div class="col-sm-12">
				<h4>Life Insurance Calculator</h4>
				<p>Find out how much life insurance you need, below:</p>
				<div class="insurance-calculator well">
					<form class="form-horizontal" role="form">
						<div class="form-group">
							<label class="col-sm-6 control-label">Funeral costs</label>
							<div class="col-sm-6">
								<input type="number" min="0" class="form-control calculator-input input-sm" placeholder="$">
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-6 control-label">Hire Purchase</label>
							<div class="col-sm-6">
								<input type="number" min="0" class="form-control calculator-input input-sm" placeholder="$">
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-6 control-label">Credit Cards</label>
							<div class="col-sm-6">
								<input type="number" min="0" class="form-control calculator-input input-sm" placeholder="$">
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-6 control-label">Other</label>
							<div class="col-sm-6">
								<input type="number" min="0" class="form-control calculator-input input-sm" placeholder="$">
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-6 control-label">Living costs (annually)</label>
							<div class="col-sm-6">
								<input type="number" min="0" class="form-control calculator-input input-sm" placeholder="$">
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-6 control-label">How many $ will living costs be required?</label>
							<div class="col-sm-6">
								<input type="number" min="0" class="form-control calculator-input input-sm" placeholder="$">
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-6 control-label">TOTAL:</label>
							<div class="col-sm-6">
								<input id="calculator-output" class="form-control input-sm" type="text" readonly>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
	<div class="col-sm-10">
		<div class="row">
			<div class="col-sm-12">
				<h3 class="about-heading">Life Insurance in Less than 8 Minutes</h3>
				<h4>No paper, no signature, no hassle!</h4>
				<p>IBrokers is proud to bring you their "one stop online insurance shop", where you can insure just about everything from your life to your boat.</p>
			</div>
		</div>
		<div class="row">
			<div class="col-sm-10">
				<ul class="nav nav-tabs buy-online-tab-header">
					<li class="active"><a href="#life-insurance" data-toggle="tab">Life</a></li>
					<li><a href="#mortgage-insurance" data-toggle="tab">Mortgage</a></li>
				</ul>
				<div class="tab-content buy-online-tabs">
					<div class="tab-pane active" id="life-insurance">
						<div class="row">
							<div class="col-sm-12">
								<h4>Life Insurance</h4>
								<div class="row">
									<div class="col-sm-9">
										<p>This insurance cover is designed to lessen the financial strain on the loved ones you leave behind in the event of your death. The lump sum payment may help them pay for immediate costs such as your funeral, and other costs such as daily bills or paying off bank loans.</p>
										<form class="form-horizontal" role="form">
											<div class="form-group">
												<label for="age-life" class="col-sm-2 control-label">Age</label>
												<div class="col-sm-10">
													<input type="number" min="1" class="form-control" id="age-life" placeholder="Years">
												</div>
											</div>
											<div class="form-group">
												<label class="col-sm-2 control-label">Gender</label>
												<div class="col-sm-10">
													<label class="radio-inline">
														<input type="radio" name="gender" value="male"> Male
													</label>
													<label class="radio-inline">
														<input type="radio" name="gender" value="female"> Female
													</label>
												</div>
											</div>
											<div class="form-group">
												<label class="col-sm-2 control-label">Are you a smoker?</label>
												<div class="col-sm-10">
													<label class="radio-inline">
														<input type="radio" name="smoker" value="male"> Yes
													</label>
													<label class="radio-inline">
														<input type="radio" name="smoker" value="female"> No
													</label>
												</div>
											</div>
											<div class="form-group">
												<label class="col-sm-2 control-label">Cover Amount (NZ$)</label>
												<div class="col-sm-10">
													<input type="text" class="bootstrap-slider">
												</div>
											</div>
											<div class="form-group">
												<div class="col-sm-offset-2 col-sm-10">
													<button type="submit" class="btn btn-default">Buy Now</button>
												</div>
											</div>
										</form>
									</div>
									<div class="col-sm-3"></div>
								</div>
							</div>
						</div>
					</div>
					<div class="tab-pane" id="mortgage-insurance">
						<div class="row">
							<div class="col-sm-12">
								<h4>Mortgage Protection Insurance</h4>
								<div class="row">
									<div class="col-sm-9">
										<p>Could your loved ones afford to keep your home in the event of your death? This insurance cover provides them with a lump sum payment which they can use to keep paying the mortgage until a decision is made about the family home.</p>
										<form class="form-horizontal" role="form">
											<div class="form-group">
												<label for="age-mortgage" class="col-sm-2 control-label">Age</label>
												<div class="col-sm-10">
													<input type="number" min="1" class="form-control" id="age-mortgage" placeholder="Years">
												</div>
											</div>
											<div class="form-group">
												<label class="col-sm-2 control-label">Gender</label>
												<div class="col-sm-10">
													<label class="radio-inline">
														<input type="radio" name="gender" value="male"> Male
													</label>
													<label class="radio-inline">
														<input type="radio" name="gender" value="female"> Female
													</label>
												</div>
											</div>
											<div class="form-group">
												<label class="col-sm-2 control-label">Are you a smoker?</label>
												<div class="col-sm-10">
													<label class="radio-inline">
														<input type="radio" name="smoker" value="male"> Yes
													</label>
													<label class="radio-inline">
														<input type="radio" name="smoker" value="female"> No
													</label>
												</div>
											</div>
											<div class="form-group">
												<label class="col-sm-2 control-label">Cover Amount (NZ$)</label>
												<div class="col-sm-10">
													<input type="text" class="bootstrap-slider" >
												</div>
											</div>
											<div class="form-group">
												<div class="col-sm-offset-2 col-sm-10">
													<button type="submit" class="btn btn-default">Buy Now</button>
												</div>
											</div>
										</form>
									</div>
									<div class="col-sm-3"></div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/welcome/index.html.erb
<div class="row imageshow">
	<div class="col-sm-4 imageshow-background advice-background">
		<div class="blur-background">
			
		</div>
		<div class="imageshow-content">
			<h2>Business Insurance</h2>
			<hr>
			<span>
				We can help you plan for tomorrow.
				<br>
				So you can live for today.
			</span>
			<div>
				<%= link_to 'Learn More', business_path, class: "btn btn-primary learn-more" %>
			</div>
		</div>
	</div>
	<div class="col-sm-4 imageshow-background retirement-background">
		<div class="blur-background">
			
		</div>
		<div class="imageshow-content">
			<h2>Life and Health</h2>
			<hr>
			<span>
				The secret to reaching your financial goals?
				<br>
				Small, manageable steps.
			</span>
			<div>
				<%= link_to 'Learn More', personal_path, class: "btn btn-primary learn-more" %>
			</div>
		</div>
	</div>
	<div class="col-sm-4 imageshow-background life-background">
		<div class="blur-background">
			
		</div>
		<div class="imageshow-content">
			<h2>Buy Online</h2>
			<hr>
			<span>
				It's more than peace of mind.
				<br>
				It's possibilities.
			</span>
			<div>
				<%= link_to "Learn More",buy_online_path, class: "btn btn-primary learn-more" %>
			</div>
		</div>
	</div>
</div>
<div class="row question">
	<h3>Not sure where to start? Our Step Ahead Guide can get you thinking. And doing. <a href="#">Step Ahead</a> </h3>
</div>
<div class="row arrow-down">
	<div class="bxslider">
		<%= render({partial: "slider", locals: {categories: @slider_categories} }) %>
	</div>
</div>

<div class="row">
	<div class="fixed-footer col-sm-12" style="position:fixed;">
		<div class="pull-right" style="margin-right:50px">
			<a href="#">Contact us at 0800-425-000</a>
		</div>
	</div>
</div>

<div class="services row">
	<div class="col-sm-12">
		<div class="row plans">
			<div class="col-sm-4">
				<h3>
					<a href="#" class="blue-link services-title">Personal</a>
				</h3>
				<a href="#" class="blue-link">Life</a>
				<br>
				<a href="#" class="blue-link">Trauma</a>
				<br>
				<a href="#" class="blue-link">Medical</a>
				<br>
				<a href="#" class="blue-link">Income</a>
				<br>
			</div>
			<div class="col-sm-4">
				<h3>
					<a href="#" class="blue-link services-title">Business</a>
				</h3>
				<a href="#" class="blue-link">Commercial</a>
				<br>
				<a href="#" class="blue-link">Home and Content</a>
				<br>
				<a href="#" class="blue-link">Property</a>
				<br>
				<a href="#" class="blue-link">Rural</a>
				<br>
			</div>
			<div class="col-sm-4">
				<h3>
					<a href="#" class="blue-link services-title">Quote</a>
				</h3>
				<a href="#" class="blue-link">Personal</a>
				<br>
				<a href="#" class="blue-link">Business</a>
				<br>
				<a href="#" class="blue-link">Home and Content</a>
				<br>
			</div>
		</div>
		<div class="row">
			<div class="col-sm-12">
				<div class="services-line-break"></div>
			</div>
		</div>
		<!-- <div class="row about-us">
			<div class="col-sm-3">
				<h3>
					<a href="#" class="blue-link services-title">About Ibrokers</a>
				</h3>
				<a href="#" class="blue-link">Newsroom</a>
				<br>
				<a href="#" class="blue-link">Careers</a>
			</div>
			<div class="col-sm-3">
				<h3>
					<a href="#" class="blue-link services-title">About Ibrokers</a>
				</h3>
				<a href="#" class="blue-link">Newsroom</a>
				<br>
				<a href="#" class="blue-link">Careers</a>
			</div>
			<div class="col-sm-3">
				<h3>
					<a href="#" class="blue-link services-title">About Ibrokers</a>
				</h3>
				<a href="#" class="blue-link">Newsroom</a>
				<br>
				<a href="#" class="blue-link">Careers</a>
			</div>
			<div class="col-sm-3">
				<h3>
					<a href="#" class="blue-link services-title">About Ibrokers</a>
				</h3>
				<a href="#" class="blue-link">Newsroom</a>
				<br>
				<a href="#" class="blue-link">Careers</a>
			</div>
		</div> -->
	</div>
</div>

app/views/welcome/insurance_partner.html.erb
<div id="banner" class="banner-default">
	<h1>Insurance Partner</h1>
</div>
<div class="banner-header">
	<div class="row imageshow">
		<div>
			<img class="insurance-partner-img" src="/assets/Colour-Logo-with-Slogan2.jpg" alt="logo">
		</div>
	</di>
</div>

app/views/welcome/why_ibrokers.html.erb
<div id="banner" class="banner-default">
	<h1>Why Use a Broker</h1>
</div>

<div class="banner-header">
	<div class="row">
		<div class="col-sm-12">
			<div>
				<p>
					We have observed and it is a proven fact that lot of people we talk to in the first conversation relating to insurance say "I already have lots of insurance". 
				</p>
				<p>
					Having insurance is good in fact you can insure almost anything under the sun, but certain things absolutely need to be properly insured. This typically includes your life, your health, and your property.
				</p>
				<p>
					While you want to ensure that you're adequately protected, there are a lot of insurance policies that are unnecessary for most people. Purchasing the wrong insurance, or simply spending too much on insurance can do more harm than good.
				</p>
				<p>
					There are thousands of combinations of different types of insurance that exist in today’s world and it is very much possible that you could be over-insured, under-insured, wrongly insured or correctly insured. No matter which of the above category you fall into, what stage of life you are at or even if you just want to make sure that you are properly covered, all you need to do is to dial our 0800 number. 
				</p>
				<p>
					Our brokers provide free of cost risk insurance review to make sure that you are insured for the things that are the most important to you.
				</p>
			</div>
		</div>
	</div>
</div>

app/views/welcome/your_risk.html.erb
<div class="row">
	<div class="col-sm-12" style="margin-top:200px;margin-left:500px">
		<p>This page is under maintenance</p>
	</div>
</div>